version: "3.1"

services:

  map:
    build: .
    restart: on-failure
    ports:
      - "80:80"
    environment:
      TEMPLATE_FILE: template.html
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}  # set key
